language: node_js
before_script:
  if [ $IS_INTEGRATION_TEST ]; then npm run development & echo "Starting App for Integration Tests"; else echo "Not an integration test. Skipping app setup"; fi
script: npm run $TEST
addons:
  hosts:
    - bs-local.com
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      - secure: JI6B1G0O1/4gNucFWDzNJXO0HkzR9IGDZ010Lofs5ZQL/FKyTAQE/9qPjS29sumPzH3ePgsiUjddiDSn51GmmHtuxrZQD9ROT480InvDJwbs2JJfjofKFliBGoTit4tU7A8kqRNiyHYS8nmZOo/lWpAuZAp8f0zQfDOQL+G+SJFTDrHJVj3LDSbY9gLRomRn28KzZpm0vX5usQRZHpaL8LtGtq/18fOPajRHeUpZW9+ZtH3PBpcMSFFjM3QyBedKMI3i1T8Uf+FCFGifjqCoAUND6mrwOGIPcn1+RdGzFquJXKqzRu4K9HCAnjRYdbY3vqR2Ced3YzQu/UjyOuBLqpulPvpL/Y1V3SH3ufO9xUSVpyaYsfF9g+Ilzfvf2QADROl12InsdV45jB6EmVoUuGHUfFXn5jU0CqTmZ+DhOZbHU81eRXbDNnD/OPkBLzZ+x0O1t1Sv4LtE2Ha5/SSAekT5h0MQeEK5O5KffGD8V8BTm00jSxvCYxtcPMXhs9Y5HBi0oiFF37Jg1bX8ex+Ga3f81URQ4/yYKzQeDlS+TOmpk2/IevyuCbZC1A9j32NaNQxnXjSVnQ/0miINptto3hXJsq5rcGdoNDb294WMN2vb4Fx+CMLZ2++q0fvNSFWbMzSO3fp7kckDyYAsQupyc+nJlvmTMmuNpq6Uiby6ocQ=
env:
  matrix:
    - TEST="lint"
    - TEST="test:unit"
    - TEST="test:integration" ONLY_BROWSERS=chrome,firefox,safari IS_INTEGRATION_TEST=true
    - TEST="test:integration" ONLY_BROWSERS=ie,edge IS_INTEGRATION_TEST=true
  global:
  - secure: ODCVx9obqlOKrbBjwACVL05KDariTYCRvaFcNTTz/TQeTcmP4OiX3WMjWPRMBnVN7mhdH2OvipRo6x3JHLi2vPSqZmCegdFpetI/C4KR0UUo0FpOhRuwhTX8eEoK1Q/aGMth0xnk+vSxfn2UTBeLQT9LBaRKKktQlIYjgqBgNLm21SaHCpYhTrVJRV96pBlfli5I1DA6KhHlL33QOT1gd+h2zbf/mP1GZlzr4a9Er2K7TUiVyVI0a8s9oxW913uKFzWY4nLHoFCrIe/ta9+5GMrYjTWHOPscFlBG6VArLQ51pIJ3wv49EWIj1zhJCiC15jtSeQAVxaZT2oHjX+m3hAeZUg4sPO5HpA3WIuI4pIuwGtgZPBbX1/abx394GdQ6F9/Y2ZQcMPdH5Bf6VSPai6tTdy8u2kJLCKclqURfu84bT9OpH7R3GPr2EiKOsplYzqJocxKwgZwNGck/h4uRIFXViazkwEQaNIGwa1G9DbjxvxZWadZApBJ0Z00MHbdGetlnaNanfBP1Yeskl3L/RVL/eW+iDsGQob3oeRV3aTuWqun4+wkU3NI6KBhuJYllo3SYsNnrqppKRvcUfxg30NKYx5A2CWBvAuTwzsfibf7kldKchGTwpby0b6wuxak8/hTbBegfO2bG07DRuEDu+CU2yCEeolUHyKW3jov5Jnc=
  - secure: I4knTurENCpe0Gs3qD7aSvNjEWLI3savuyNGanD6s6fjovpbAoiBnc+nqVuFuvfBBvRWM1CNq6fbxxuE+BRvaX8MymP5Fe1Q5hGCUAke+9gIGueb/4QltI07CEpt85E9CWJZCPtVNHO8q6N7v1IrbmeEl5k4TnfbmtXHEW4So1bg4rNSsThVzMKVeJyHNfSouehEsDZhdLVKEr5m7mwfB9GGwiW4NdHM2fEcda6ZTUnUP6q6m7XU4tSO8aWWdnpbDpzh4X7UHWWL14kE1q6c0gdjr0se9+sxog7MvAcU2KBkggPIN9X+u8/Ybc4tOBtM05R2kp4btCxZvuDSuYH5R1v9K7ohqxZcOdPWhpUZNT4AfeGLBxOW//yWTa59E0Rq+ALMBK5+fEOD3KoA6funBN8awoknKIJW+PUsjiyX+RUlBWCCjl+cFh5Zqvb7vHQoqEZiTj6mq1BTkLubIaVFwR7NdBPjo/Ef0Ch+sQjQk7YP9EQrvJ9psYLt62M0kKc5etExQss0q7OIlj7jmTo5sfG50egJnBPmayX0HIUw3/5k9L5BfShVfudQfMulKWFfIXqJNgO8OlVulaupD2lkFgd4o5HJwVGPqY03dvVs/p9APuOb5OPk5+XHH+10UZ13uL7M/tyKsVNet3HZ+Sgw2hEGgJclPCJkFbnvH+ePMuU=
