language: node_js
before_install:
  touch .env;
  if [ $IS_INTEGRATION_TEST ]; then rvm install ruby-2.4.3 --binary && rvm use ruby-2.4.3 && bundle install; else echo "Not an integration test. Skipping Ruby setup"; fi
script: npm run $TEST
addons:
  hosts:
    - restricted-input.bt.local
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      - secure: JI6B1G0O1/4gNucFWDzNJXO0HkzR9IGDZ010Lofs5ZQL/FKyTAQE/9qPjS29sumPzH3ePgsiUjddiDSn51GmmHtuxrZQD9ROT480InvDJwbs2JJfjofKFliBGoTit4tU7A8kqRNiyHYS8nmZOo/lWpAuZAp8f0zQfDOQL+G+SJFTDrHJVj3LDSbY9gLRomRn28KzZpm0vX5usQRZHpaL8LtGtq/18fOPajRHeUpZW9+ZtH3PBpcMSFFjM3QyBedKMI3i1T8Uf+FCFGifjqCoAUND6mrwOGIPcn1+RdGzFquJXKqzRu4K9HCAnjRYdbY3vqR2Ced3YzQu/UjyOuBLqpulPvpL/Y1V3SH3ufO9xUSVpyaYsfF9g+Ilzfvf2QADROl12InsdV45jB6EmVoUuGHUfFXn5jU0CqTmZ+DhOZbHU81eRXbDNnD/OPkBLzZ+x0O1t1Sv4LtE2Ha5/SSAekT5h0MQeEK5O5KffGD8V8BTm00jSxvCYxtcPMXhs9Y5HBi0oiFF37Jg1bX8ex+Ga3f81URQ4/yYKzQeDlS+TOmpk2/IevyuCbZC1A9j32NaNQxnXjSVnQ/0miINptto3hXJsq5rcGdoNDb294WMN2vb4Fx+CMLZ2++q0fvNSFWbMzSO3fp7kckDyYAsQupyc+nJlvmTMmuNpq6Uiby6ocQ=
env:
  matrix:
    - TEST="lint"
    - TEST="test:unit"
    - TEST="test:integration" IS_INTEGRATION_TEST=true HOSTNAME=restricted-input.bt.local
  global:
  - secure: v655z9rG83zEh+3DRS4ck0GidJAj2nkR4k1xOf+eCQYgdjNna+0PW6niL1+FefIxipe424XKMO4dULRRHMT2HvQP8gW+5ob7XZRZuqVl0nkRLtV7kx8QyIUi3zuN+SsEgUO/un0js+buu27pB6rK+KTSY24XRunKhrZku49KG+KUyVsTF51CLq9n4hCzXoZBOED41tGANMM0jFoNNhEyu5uAYcoudfUmiJsNsLNBs+iC/V2y8/PuW9CGTCd5zvFI2ONHGuwH3lfkWamy3nDNAjbzIJbDeLEO8FPSAtpUkS/qQrz3OICsse0OyZYnDTS++LryPTAFkKKwxwNpBPpy9k2BOm16Ix2wL/YXD7Oq+LhG0T+ERJZNkNY1LuBZHEEVnp7s/8/ep6I/o/NFUaKg0Nl3LZHUxpTe5LgI24mO7uZaclRH99ZJefCE/k46tZgeqqZHdUtAOE754MqtN+5ElY8oI7mbQLk8nJ4cMx/dTTOQyzhvsDBMHx/bdBccLKMJPfX5fYh0BucRUICY28ufJJ5vzleAW140+21ZqVtlnJSCoCzBuVSjGhj1CMeCd4TCfCJg6zgVx7SBn7lWzPgYNkFdwNvjwQn0YTy6ezOoIBFo08ecfygalXOmSjx7GbBoJS3DrSDh/aso2X52kIxvgf+qvu4fvfzqTbnqqMG34Q8=
  - secure: e44/E5GacLPnV+HkK7YeugyKVwi3F/Ek0gi2BAP2HI7FrjNa546ita1Oh+zEEbRapfJrLSzXbiYFx5uOyEsOvRNKVP9p/u7ggLFCldvUG4O/Dq2uSG+S1Wjd/nTmL/spdsgQP/rC3lBRBc2tdTViutidMLm+TUCBvez974ibhtBEdG5op4n4HxdR1LxWbRAn8P9fdyb/2WBBy/4LmbjKk0Z9vkVErCJwEPaBLRQSXt5+i2MTbcrr0tmGbcEzSwst0F5DjJTR5IeaxabOKkQnjvFKxMucc/VxnojZeTWMWUdqKfCu/lq8uB+5mUEd+VR5GbsnoDR0yyj6TV9x2BELeqg38ImkTwX051lTZD+0eIVKrY0qPJV8hehg9P6cf45KCyxJl5Muwaj0KgpCPDqiEmQJ3aj5B1SAbChkeUPpB4cDFiOnqMF49yQg8eWAlyv/IO8I2+iVji1X1AJodboPUUbwAf7XuoHCtvlmC08Xjp45708qPPqPHSEKAtn1d4H8J/+CUAUHZr9txNZdQFSIU6qL9WGpAWJOaUGFNUPxgDNcGPF9M/+3T/Jm+oE09EWWpRaDBqLV4UmwRxhNDCtk/beqx5TLiiZd0s1+DWGysFX4gBs2b0o5c6/8y2e5NgMCAfG1o7bymPV2jePnZ8PYQI1wRx9N3Sgr/Is2+qezUxg=
